name: mobile_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI Icons
  cupertino_icons: ^1.0.8

  # Firebase Core
  firebase_core: ^3.8.0

  # Firebase Auth for OTP login
  firebase_auth: ^5.1.0

  # Firestore backend
  cloud_firestore: ^5.6.12

  cloud_functions: ^5.6.2
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  confetti: ^0.7.0

  image_picker: ^1.0.7
  firebase_storage: ^12.4.10
  path: ^1.9.0
  lottie: ^3.1.2
  url_launcher: ^6.2.5
  clipboard: ^0.1.3
  firebase_app_check: ^0.3.2+10
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^17.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/splash/splash.png
    - assets/icon/app_icon.png
    - assets/lottie/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

  android_12:
    image_path: "assets/icon/app_icon.png"
    icon_background_color: "#2A0F4D" 

flutter_native_splash:
  color: "#2A0F4D"        # Royal red background
  image: assets/splash/splash.png

  android: true
  ios: true
  web: false

  android_12:
    color: "#2A0F4D"
    image: assets/splash/splash.png
